feat: enable queryFeeds without watch: true (#75)
🎫 Ticket:
https://linear.app/stream/issue/REACT-491/integrate-unwatch-endpoint,
https://linear.app/stream/issue/REACT-469/update-state-in-response-to-followunfollow-http-response

### 💡 Overview

The goal of this PR is to enable `queryFeeds` to work with `watch:
false`.

This requires state updates in response to "admin" endpoints. For now
state update only happens in response to follow/unfollow endpoints.

### 📝 Implementation notes

New:
- Integrate the `stopWatching` endpoint, and store `watch` in feed state
- For `follow`, `followBatch` and `unfollow` do state update
- We need to add checks to prevent duplicate state updates - thanks for
@isekovanic for this logic
([code](https://github.com/GetStream/stream-feeds-js/pull/75/files#diff-5fe26340feefe9212a93cb4f25c7996731c1245bb6253d4c106ef98afbcc3a17))

Changed:
- followers/followings are not stored if their current value is
`undefined` -> integrators can init the state with load methods
- if followers/followings are initialized, we add follower/following to
the start of the list
- when we paginate we need to filter duplications - thanks
@arnautov-anton for the `uniqueMerge` method
([code](https://github.com/GetStream/stream-feeds-js/pull/75/files#diff-20886f4c7cbf4a14b78ed974d55bb6d44f278117f37d1864e494443c3ee8f73dR30))

Sample app
- For visiting the user profile we do `getOrCreate{watch: true}` then
unwatch when leaving the page
- For `queryFeeds` we use `watch: false`

@isekovanic fixed an eslint issue `TypeError:
context.getDeclaredVariables is not a function` with version updates,
thanks

---------

Co-authored-by: Ivan Sekovanikj <ivan.sekovanikj@getstream.io>
Co-authored-by: Anton Arnautov <arnautov.anton@gmail.com>